In [137]:
# Import Dependencies
import pandas as pd
import numpy as np
import os
from sklearn.metrics import confusion_matrix

In [138]:
# Make a reference to the crimes.csv file path
csv_path = "Resources/Crimes_2019.csv"

# Import the crimes.csv file as a DataFrame
crimes_2019 = pd.read_csv(csv_path, encoding="utf-8")
crimes_2019.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Longitude,Location,Historical Wards 2003-2015,Zip Codes,Community Areas,Census Tracts,Wards,Boundaries - ZIP Codes,Police Districts,Police Beats
0,11865111,JC477762,9/21/2019 0:00,036XX W 62ND ST,1750,OFFENSE INVOLVING CHILDREN,CHILD ABUSE,RESIDENTIAL YARD (FRONT/BACK),False,True,...,-87.713894,"(41.7806197, -87.713893847)",23.0,"21,867",63.0,339.0,6.0,58.0,13.0,276.0
1,11865784,JC478477,9/30/2019 12:00,021XX W ARTHUR AVE,5002,OTHER OFFENSE,OTHER VEHICLE OFFENSE,RESIDENCE,False,True,...,-87.683325,"(41.999652591, -87.683324684)",42.0,"22,528",20.0,320.0,27.0,12.0,11.0,46.0
2,11862475,JC474623,10/16/2019 9:59,017XX W 79TH ST,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,STREET,True,False,...,-87.667398,"(41.750304023, -87.667398352)",18.0,"21,554",70.0,574.0,31.0,59.0,20.0,231.0
3,11862816,JC475002,10/16/2019 14:35,071XX S RIDGELAND AVE,486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,...,-87.582410,"(41.764807775, -87.582410292)",32.0,"22,538",39.0,452.0,37.0,24.0,18.0,217.0
4,11868795,JC482189,10/13/2019 21:40,027XX N CLARK ST,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,DEPARTMENT STORE,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
# Remove null values
crimes_2019_complete=crimes_2019.dropna()

In [140]:
# Reduce file removing unnecessary columns (including arrest column)
reduced_2019 = crimes_2019_complete.drop(["Date", "ID", "Case Number", "Block", "IUCR", "Description", "X Coordinate", "Y Coordinate", "Year", "Updated On",\
                             "Latitude", "Longitude", "Location","Boundaries - ZIP Codes", "Zip Codes","Historical Wards 2003-2015"\
                            ,"Census Tracts","Police Beats", "Police Districts","Community Areas", "Wards", "FBI Code","Location Description"], axis=1)
reduced_2019.head()

,Primary Type,Arrest,Domestic,Beat,District,Ward,Community Area
0,OFFENSE INVOLVING CHILDREN,False,True,823,8,23.0,65.0
1,OTHER OFFENSE,False,True,2412,24,50.0,2.0
2,WEAPONS VIOLATION,True,False,611,6,17.0,71.0
3,BATTERY,True,True,324,3,7.0,43.0
5,ASSAULT,False,False,331,3,5.0,43.0

In [141]:
# Use Pandas to get_dummies to convert categorical data
data_2019 = pd.get_dummies(reduced_2019)
data_2019.head()

,Arrest,Domestic,Beat,District,Ward,Community Area,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,...,Primary Type_OTHER NARCOTIC VIOLATION,Primary Type_OTHER OFFENSE,Primary Type_PROSTITUTION,Primary Type_PUBLIC INDECENCY,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION
0,False,True,823,8,23.0,65.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,False,True,2412,24,50.0,2.0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,True,False,611,6,17.0,71.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,True,True,324,3,7.0,43.0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,False,False,331,3,5.0,43.0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [142]:
# Reduce file removing unnecessary columns (including arrest column)
data_2019_no_arrests = data_2019.drop(["Arrest"], axis=1)
data_2019_no_arrests.head()

,Domestic,Beat,District,Ward,Community Area,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,Primary Type_CONCEALED CARRY LICENSE VIOLATION,...,Primary Type_OTHER NARCOTIC VIOLATION,Primary Type_OTHER OFFENSE,Primary Type_PROSTITUTION,Primary Type_PUBLIC INDECENCY,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION
0,True,823,8,23.0,65.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,True,2412,24,50.0,2.0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,False,611,6,17.0,71.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,True,324,3,7.0,43.0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,False,331,3,5.0,43.0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [143]:
# Push the remade DataFrame to a new CSV file
data_2019_no_arrests.to_csv("Output/data_2019.csv",
                  encoding="utf-8", index=False, header=True)

### We have the data saved into a file.

In [144]:
# Load the model
from sklearn.externals import joblib
model = joblib.load("./chicago-crime-trained-model-Frances.pkl")

In [145]:
# make predictions
model.predict(data_2019_no_arrests)

array([False, False,  True, ..., False, False, False])

In [146]:
# add arrest prediction to df
data_2019["Arrest_Prediction"]=model.predict(data_2019_no_arrests)
data_2019.head

<bound method NDFrame.head of         Arrest  Domestic  Beat  District  Ward  Community Area  \
0        False      True   823         8  23.0            65.0
1        False      True  2412        24  50.0             2.0
2         True     False   611         6  17.0            71.0
3         True      True   324         3   7.0            43.0
5        False     False   331         3   5.0            43.0
6        False     False   922         9  15.0            58.0
7        False      True   433         4  10.0            55.0
8         True     False   523         5   9.0            53.0
9        False     False  2525        25  35.0            22.0
10       False      True  1522        15  29.0            25.0
11       False      True   726         7  17.0            67.0
14       False     False   932         9  16.0            61.0
15       False     False  2432        24  40.0             1.0
17       False     False   731         7   6.0            69.0
18       False     False  2522        25  36.0            19.0
19       False     False   731         7   6.0            69.0
20       False     False  1422        14  26.0            23.0
22       False     False  1712        17  39.0            14.0
23       False     False  2221        22  21.0            73.0
24       False      True  2512        25  36.0            19.0
25       False     False  1533        15  28.0            25.0
26       False     False   112         1  42.0            32.0
27       False     False   114         1  42.0            32.0
28       False      True   214         2   3.0            38.0
29       False     False  1811        18   2.0             7.0
30       False     False   934         9  20.0            61.0
31       False     False  1522        15  28.0            25.0
32       False      True   413         4   8.0            51.0
33        True     False   611         6  21.0            71.0
34       False     False  1224        12  27.0            28.0
...        ...       ...   ...       ...   ...             ...
206422   False     False   915         9   3.0            34.0
206423   False     False  1011        10  24.0            29.0
206424   False     False  1423        14  26.0            24.0
206425   False     False  1112        11  27.0            23.0
206426   False     False  1124        11  28.0            27.0
206427   False     False   715         7  15.0            67.0
206428   False     False  1132        11  28.0            26.0
206429   False     False  1132        11  24.0            26.0
206430   False     False   725         7  16.0            67.0
206431   False     False   213         2   3.0            35.0
206432   False     False  1533        15  28.0            25.0
206433   False     False  1511        15  29.0            25.0
206434   False     False  1211        12   1.0            24.0
206435   False     False   412         4   8.0            45.0
206436    True     False   522         5  34.0            49.0
206437   False     False  1124        11  28.0            27.0
206438   False     False   513         5  34.0            49.0
206439   False     False   422         4   7.0            46.0
206440    True     False   834         8  18.0            70.0
206441   False     False   333         3   5.0            43.0
206442   False     False   412         4   7.0            46.0
206443   False     False  1011        10  24.0            29.0
206444   False     False  1531        15  37.0            25.0
206445   False     False  1224        12  27.0            28.0
206446   False     False   623         6   6.0            69.0
206447   False     False   832         8  17.0            66.0
206448   False      True   726         7  16.0            67.0
206449   False     False   713         7  16.0            67.0
206450   False     False   513         5  34.0            49.0
206451   False     False   621         6  17.0            69.0

        Primary Type_ARSON  Primary Type_ASSAULT  Primary Type_BATTERY  \
0                        0                     0                     0
1                        0                     0                     0
2                        0                     0                     0
3                        0                     0                     1
5                        0                     1                     0
6                        0                     0                     0
7                        0                     0                     0
8                        0                     0                     0
9                        0                     0                     0
10                       0                     1                     0
11                       0                     0                     1
14                       0                     0                     0
15                       0                     0                     0
17                       0                     0                     0
18                       0                     1                     0
19                       0                     0                     0
20                       0                     0                     1
22                       0                     0                     0
23                       0                     0                     0
24                       0                     0                     0
25                       0                     0                     0
26                       0                     0                     0
27                       0                     0                     0
28                       0                     0                     1
29                       0                     0                     0
30                       0                     0                     0
31                       0                     0                     0
32                       0                     0                     0
33                       0                     0                     0
34                       0                     0                     0
...                    ...                   ...                   ...
206422                   0                     0                     0
206423                   0                     0                     0
206424                   0                     0                     0
206425                   0                     0                     0
206426                   0                     0                     0
206427                   0                     0                     0
206428                   0                     0                     0
206429                   0                     0                     0
206430                   0                     0                     0
206431                   0                     0                     0
206432                   0                     0                     0
206433                   0                     0                     0
206434                   0                     0                     0
206435                   0                     0                     0
206436                   0                     0                     0
206437                   0                     0                     0
206438                   0                     0                     0
206439                   0                     0                     0
206440                   0                     0                     0
206441                   0                     0                     0
206442                   0                     0                     0
206443                   0                     0                     0
206444                   0                     0                     0
206445                   0                     0                     0
206446                   0                     0                     0
206447                   0                     0                     0
206448                   0                     0                     0
206449                   0                     0                     0
206450                   0                     0                     0
206451                   0                     0                     0

        Primary Type_BURGLARY  ...  Primary Type_OTHER OFFENSE  \
0                           0  ...                           0
1                           0  ...                           1
2                           0  ...                           0
3                           0  ...                           0
5                           0  ...                           0
6                           0  ...                           0
7                           0  ...                           0
8                           0  ...                           0
9                           0  ...                           0
10                          0  ...                           0
11                          0  ...                           0
14                          0  ...                           0
15                          0  ...                           0
17                          1  ...                           0
18                          0  ...                           0
19                          0  ...                           0
20                          0  ...                           0
22                          0  ...                           0
23                          0  ...                           1
24                          0  ...                           0
25                          0  ...                           0
26                          0  ...                           0
27                          0  ...                           0
28                          0  ...                           0
29                          0  ...                           0
30                          0  ...                           1
31                          0  ...                           0
32                          0  ...                           1
33                          0  ...                           0
34                          0  ...                           0
...                       ...  ...                         ...
206422                      0  ...                           0
206423                      0  ...                           0
206424                      0  ...                           0
206425                      0  ...                           0
206426                      0  ...                           0
206427                      0  ...                           0
206428                      0  ...                           0
206429                      0  ...                           0
206430                      0  ...                           0
206431                      0  ...                           0
206432                      0  ...                           0
206433                      0  ...                           0
206434                      0  ...                           0
206435                      0  ...                           0
206436                      0  ...                           0
206437                      0  ...                           0
206438                      0  ...                           0
206439                      0  ...                           0
206440                      0  ...                           0
206441                      0  ...                           0
206442                      0  ...                           0
206443                      0  ...                           0
206444                      0  ...                           0
206445                      0  ...                           0
206446                      0  ...                           0
206447                      0  ...                           0
206448                      0  ...                           0
206449                      0  ...                           0
206450                      0  ...                           0
206451                      0  ...                           0

        Primary Type_PROSTITUTION  Primary Type_PUBLIC INDECENCY  \
0                               0                              0
1                               0                              0
2                               0                              0
3                               0                              0
5                               0                              0
6                               0                              0
7                               0                              0
8                               0                              0
9                               0                              0
10                              0                              0
11                              0                              0
14                              0                              0
15                              0                              0
17                              0                              0
18                              0                              0
19                              0                              0
20                              0                              0
22                              0                              0
23                              0                              0
24                              0                              0
25                              0                              0
26                              0                              0
27                              0                              0
28                              0                              0
29                              0                              0
30                              0                              0
31                              0                              0
32                              0                              0
33                              0                              0
34                              0                              0
...                           ...                            ...
206422                          0                              0
206423                          0                              0
206424                          0                              0
206425                          0                              0
206426                          0                              0
206427                          0                              0
206428                          0                              0
206429                          0                              0
206430                          0                              0
206431                          0                              0
206432                          0                              0
206433                          0                              0
206434                          0                              0
206435                          0                              0
206436                          0                              0
206437                          0                              0
206438                          0                              0
206439                          0                              0
206440                          0                              0
206441                          0                              0
206442                          0                              0
206443                          0                              0
206444                          0                              0
206445                          0                              0
206446                          0                              0
206447                          0                              0
206448                          0                              0
206449                          0                              0
206450                          0                              0
206451                          0                              0

        Primary Type_PUBLIC PEACE VIOLATION  Primary Type_ROBBERY  \
0                                         0                     0
1                                         0                     0
2                                         0                     0
3                                         0                     0
5                                         0                     0
6                                         0                     0
7                                         0                     0
8                                         0                     0
9                                         0                     0
10                                        0                     0
11                                        0                     0
14                                        0                     0
15                                        0                     0
17                                        0                     0
18                                        0                     0
19                                        0                     0
20                                        0                     0
22                                        0                     0
23                                        0                     0
24                                        0                     0
25                                        0                     0
26                                        0                     0
27                                        0                     0
28                                        0                     0
29                                        0                     0
30                                        0                     0
31                                        0                     0
32                                        0                     0
33                                        0                     0
34                                        1                     0
...                                     ...                   ...
206422                                    0                     0
206423                                    0                     0
206424                                    0                     0
206425                                    0                     0
206426                                    0                     0
206427                                    0                     0
206428                                    0                     0
206429                                    0                     0
206430                                    0                     0
206431                                    0                     0
206432                                    0                     0
206433                                    0                     0
206434                                    0                     0
206435                                    0                     0
206436                                    0                     0
206437                                    0                     0
206438                                    0                     0
206439                                    0                     0
206440                                    0                     0
206441                                    0                     0
206442                                    0                     0
206443                                    0                     0
206444                                    0                     0
206445                                    0                     0

In [147]:
# add column to determine if prediction is accurate
data_2019["Correct_Prediction?"] = np.where(data_2019.Arrest_Prediction == data_2019.Arrest, 'True', 'False')
data_2019.head()

,Arrest,Domestic,Beat,District,Ward,Community Area,Primary Type_ARSON,Primary Type_ASSAULT,Primary Type_BATTERY,Primary Type_BURGLARY,...,Primary Type_PROSTITUTION,Primary Type_PUBLIC INDECENCY,Primary Type_PUBLIC PEACE VIOLATION,Primary Type_ROBBERY,Primary Type_SEX OFFENSE,Primary Type_STALKING,Primary Type_THEFT,Primary Type_WEAPONS VIOLATION,Arrest_Prediction,Correct_Prediction?
0,False,True,823,8,23.0,65.0,0,0,0,0,...,0,0,0,0,0,0,0,0,False,True
1,False,True,2412,24,50.0,2.0,0,0,0,0,...,0,0,0,0,0,0,0,0,False,True
2,True,False,611,6,17.0,71.0,0,0,0,0,...,0,0,0,0,0,0,0,1,True,True
3,True,True,324,3,7.0,43.0,0,0,1,0,...,0,0,0,0,0,0,0,0,False,False
5,False,False,331,3,5.0,43.0,0,1,0,0,...,0,0,0,0,0,0,0,0,False,True

In [148]:
# provide prediction result counts
data_2019["Correct_Prediction?"].value_counts()

True     176662
False     27124
Name: Correct_Prediction?, dtype: int64

In [149]:
data_2019["Arrest"].count()

203786

In [150]:
# calculate model accuracy
print("{0:0.2f}% Accuracy achieved by the model".format(176662/len(data_2019.index) * 100))

86.69% Accuracy achieved by the model