## We evaluate the trained model which used Random Forest algorithm

In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from IPython.display import IFrame
from IPython.core.display import display
import os
import time
import seaborn as sns

### Remove Arrest column from evaluation data since we will be prediction Arrests

In [2]:
# get data from truncated chicago crime 500 rows data file
df_predict = pd.read_csv("./Crime_last500.csv")
print(df_predict.shape)

(500, 29)

In [3]:

df_predict_arrest = pd.DataFrame([ df_predict.IUCR, df_predict.sin_time ,df_predict.cos_time, df_predict.XAxis, df_predict.YAxis]).transpose()

In [5]:
df_predict_arrest.head(5)

     IUCR      sin_time  cos_time      XAxis      YAxis
0  1310.0 -2.449294e-16       1.0  1168528.0  1858699.0
1  2092.0 -2.449294e-16       1.0  1150216.0  1899724.0
2   454.0 -2.449294e-16       1.0  1153327.0  1890804.0
3   820.0 -2.449294e-16       1.0  1161813.0  1912993.0
4  1320.0 -2.449294e-16       1.0  1188500.0  1842375.0

## Load the saved model

In [6]:
from sklearn.externals import joblib
lr_cv_model = joblib.load("./chicago-crime-trained-LR500model.pkl")

In [7]:
X_predict = df_predict_arrest

In [8]:
lr_cv_model.predict(X_predict)

array([1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [9]:
df_predict_arrest['Arrest_Predicted']=lr_cv_model.predict(X_predict)

In [11]:
df_predict_arrest.head(5)

     IUCR      sin_time  cos_time      XAxis      YAxis  Arrest_Predicted
0  1310.0 -2.449294e-16       1.0  1168528.0  1858699.0                 1
1  2092.0 -2.449294e-16       1.0  1150216.0  1899724.0                 1
2   454.0 -2.449294e-16       1.0  1153327.0  1890804.0                 0
3   820.0 -2.449294e-16       1.0  1161813.0  1912993.0                 0
4  1320.0 -2.449294e-16       1.0  1188500.0  1842375.0                 1

In [12]:
df_predict_arrest['Actual_Arrest'] = pd.DataFrame([df_predict.Arrest]).transpose()

In [13]:
df_predict_arrest.head(20)

,IUCR,sin_time,cos_time,XAxis,YAxis,Arrest_Predicted,Actual_Arrest
0,1310.0,-2.449294e-16,1.0,1168528.0,1858699.0,1,0
1,2092.0,-2.449294e-16,1.0,1150216.0,1899724.0,1,1
2,454.0,-2.449294e-16,1.0,1153327.0,1890804.0,0,0
3,820.0,-2.449294e-16,1.0,1161813.0,1912993.0,0,0
4,1320.0,-2.449294e-16,1.0,1188500.0,1842375.0,1,1
5,860.0,-2.449294e-16,1.0,1161164.0,1873304.0,0,0
6,1822.0,-2.449294e-16,1.0,1150922.0,1904715.0,1,1
7,1360.0,-2.449294e-16,1.0,1160182.0,1869437.0,1,1
8,502.0,-2.449294e-16,1.0,1170403.0,1862710.0,0,0
9,460.0,-2.449294e-16,1.0,1178582.0,1903456.0,0,1
10,560.0,-2.449294e-16,1.0,1160206.0,1896299.0,0,0
11,820.0,-2.449294e-16,1.0,1184911.0,1853289.0,0,0
12,910.0,-2.449294e-16,1.0,1162429.0,1910236.0,0,0
13,1320.0,-2.449294e-16,1.0,1169614.0,1867393.0,1,0
14,1365.0,-2.449294e-16,1.0,1165952.0,1907936.0,1,0
15,1310.0,-2.449294e-16,1.0,1177834.0,1830036.0,1,0
16,1480.0,-2.449294e-16,1.0,1149747.0,1860508.0,1,0
17,486.0,-2.449294e-16,1.0,1152506.0,1919030.0,0,1
18,51.0,-2.449294e-16,1.0,1165397.0,1951469.0,0,0
19,620.0,-2.449294e-16,1.0,1142152.0,1899086.0,0,0

In [14]:
export_csv = df_predict_arrest.to_csv (r'df_predict_arrest_LR.csv', index = None, header=True)

In [16]:
import numpy as np
df_predict_arrest['resultmatch?'] = np.where(df_predict_arrest.Arrest_Predicted == df_predict_arrest.Actual_Arrest, 'True', 'False')

In [17]:
df_predict_arrest.head(20)

,IUCR,sin_time,cos_time,XAxis,YAxis,Arrest_Predicted,Actual_Arrest,resultmatch?
0,1310.0,-2.449294e-16,1.0,1168528.0,1858699.0,1,0,False
1,2092.0,-2.449294e-16,1.0,1150216.0,1899724.0,1,1,True
2,454.0,-2.449294e-16,1.0,1153327.0,1890804.0,0,0,True
3,820.0,-2.449294e-16,1.0,1161813.0,1912993.0,0,0,True
4,1320.0,-2.449294e-16,1.0,1188500.0,1842375.0,1,1,True
5,860.0,-2.449294e-16,1.0,1161164.0,1873304.0,0,0,True
6,1822.0,-2.449294e-16,1.0,1150922.0,1904715.0,1,1,True
7,1360.0,-2.449294e-16,1.0,1160182.0,1869437.0,1,1,True
8,502.0,-2.449294e-16,1.0,1170403.0,1862710.0,0,0,True
9,460.0,-2.449294e-16,1.0,1178582.0,1903456.0,0,1,False
10,560.0,-2.449294e-16,1.0,1160206.0,1896299.0,0,0,True
11,820.0,-2.449294e-16,1.0,1184911.0,1853289.0,0,0,True
12,910.0,-2.449294e-16,1.0,1162429.0,1910236.0,0,0,True
13,1320.0,-2.449294e-16,1.0,1169614.0,1867393.0,1,0,False
14,1365.0,-2.449294e-16,1.0,1165952.0,1907936.0,1,0,False
15,1310.0,-2.449294e-16,1.0,1177834.0,1830036.0,1,0,False
16,1480.0,-2.449294e-16,1.0,1149747.0,1860508.0,1,0,False
17,486.0,-2.449294e-16,1.0,1152506.0,1919030.0,0,1,False
18,51.0,-2.449294e-16,1.0,1165397.0,1951469.0,0,0,True
19,620.0,-2.449294e-16,1.0,1142152.0,1899086.0,0,0,True

In [18]:
df_predict_arrest['resultmatch?'].value_counts()

True     332
False    168
Name: resultmatch?, dtype: int64

In [20]:
print("{0:0.2f}% Accuracy achieved by the model".format(332/len(df_predict_arrest.index) * 100))

66.40% Accuracy achieved by the model